# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\izzet\PycharmProjects\pythonProject\HesapTasarım2.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(280, 409)
        MainWindow.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.yuzde = QtWidgets.QPushButton(self.centralwidget)
        self.yuzde.setGeometry(QtCore.QRect(140, 60, 70, 70))
        self.yuzde.setObjectName("yuzde")
        self.arti = QtWidgets.QPushButton(self.centralwidget)
        self.arti.setGeometry(QtCore.QRect(210, 130, 70, 70))
        self.arti.setObjectName("arti")
        self.eksi = QtWidgets.QPushButton(self.centralwidget)
        self.eksi.setGeometry(QtCore.QRect(210, 200, 70, 70))
        self.eksi.setObjectName("eksi")
        self.carpi = QtWidgets.QPushButton(self.centralwidget)
        self.carpi.setGeometry(QtCore.QRect(210, 270, 70, 70))
        self.carpi.setObjectName("carpi")
        self.esittir = QtWidgets.QPushButton(self.centralwidget)
        self.esittir.setGeometry(QtCore.QRect(210, 60, 70, 70))
        self.esittir.setObjectName("esittir")
        self.bolu = QtWidgets.QPushButton(self.centralwidget)
        self.bolu.setGeometry(QtCore.QRect(210, 340, 70, 70))
        self.bolu.setObjectName("bolu")
        self.nokta = QtWidgets.QPushButton(self.centralwidget)
        self.nokta.setGeometry(QtCore.QRect(140, 340, 70, 70))
        self.nokta.setStyleSheet("background-color: rgb(170, 85, 0);\n"
"font: 75 18pt \"MS Shell Dlg 2\";\n"
"color: rgb(170, 255, 0);")
        self.nokta.setObjectName("nokta")
        self.buton0 = QtWidgets.QPushButton(self.centralwidget)
        self.buton0.setGeometry(QtCore.QRect(-1, 340, 141, 70))
        self.buton0.setStyleSheet("background-color: rgb(148, 153, 152);\n"
"font: 75 18pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 127);")
        self.buton0.setObjectName("buton0")
        self.buton6 = QtWidgets.QPushButton(self.centralwidget)
        self.buton6.setGeometry(QtCore.QRect(140, 200, 70, 70))
        self.buton6.setStyleSheet("background-color: rgb(148, 153, 152);\n"
"font: 75 18pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 127);")
        self.buton6.setObjectName("buton6")
        self.buton7 = QtWidgets.QPushButton(self.centralwidget)
        self.buton7.setGeometry(QtCore.QRect(0, 130, 70, 70))
        self.buton7.setStyleSheet("background-color: rgb(148, 153, 152);\n"
"font: 75 18pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 127);")
        self.buton7.setObjectName("buton7")
        self.buton8 = QtWidgets.QPushButton(self.centralwidget)
        self.buton8.setGeometry(QtCore.QRect(70, 130, 70, 70))
        self.buton8.setStyleSheet("background-color: rgb(148, 153, 152);\n"
"font: 75 18pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 127);")
        self.buton8.setObjectName("buton8")
        self.buton4 = QtWidgets.QPushButton(self.centralwidget)
        self.buton4.setGeometry(QtCore.QRect(0, 200, 70, 70))
        self.buton4.setStyleSheet("background-color: rgb(148, 153, 152);\n"
"font: 75 18pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 127);")
        self.buton4.setObjectName("buton4")
        self.buton5 = QtWidgets.QPushButton(self.centralwidget)
        self.buton5.setGeometry(QtCore.QRect(70, 200, 70, 70))
        self.buton5.setStyleSheet("background-color: rgb(148, 153, 152);\n"
"font: 75 18pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 127);")
        self.buton5.setObjectName("buton5")
        self.buton3 = QtWidgets.QPushButton(self.centralwidget)
        self.buton3.setGeometry(QtCore.QRect(140, 270, 70, 70))
        self.buton3.setStyleSheet("background-color: rgb(148, 153, 152);\n"
"font: 75 18pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 127);")
        self.buton3.setObjectName("buton3")
        self.buton1 = QtWidgets.QPushButton(self.centralwidget)
        self.buton1.setGeometry(QtCore.QRect(0, 270, 70, 70))
        self.buton1.setStyleSheet("background-color: rgb(148, 153, 152);\n"
"font: 75 18pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 127);")
        self.buton1.setObjectName("buton1")
        self.buton2 = QtWidgets.QPushButton(self.centralwidget)
        self.buton2.setGeometry(QtCore.QRect(70, 270, 70, 70))
        self.buton2.setStyleSheet("background-color: rgb(148, 153, 152);\n"
"font: 75 18pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 127);")
        self.buton2.setObjectName("buton2")
        self.buton9 = QtWidgets.QPushButton(self.centralwidget)
        self.buton9.setGeometry(QtCore.QRect(140, 130, 70, 70))
        self.buton9.setStyleSheet("background-color: rgb(148, 153, 152);\n"
"font: 75 18pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 127);")
        self.buton9.setObjectName("buton9")
        self.clear = QtWidgets.QPushButton(self.centralwidget)
        self.clear.setGeometry(QtCore.QRect(0, 60, 141, 70))
        self.clear.setObjectName("clear")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 281, 61))
        font = QtGui.QFont()
        font.setFamily("MS UI Gothic")
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("Hesap Makinesi", "Hesap Makinesi"))
        self.yuzde.setStyleSheet(_translate("MainWindow", "background-color: rgb(170, 85, 0);\n"
"font: 75 18pt \"MS Shell Dlg 2\";\n"
"color: rgb(170, 255, 0);"))
        self.yuzde.setText(_translate("MainWindow", "%"))
        self.arti.setStyleSheet(_translate("MainWindow", "background-color: rgb(170, 85, 0);\n"
"font: 75 18pt \"MS Shell Dlg 2\";\n"
"color: rgb(170, 255, 0);"))
        self.arti.setText(_translate("MainWindow", "+"))
        self.eksi.setStyleSheet(_translate("MainWindow", "background-color: rgb(170, 85, 0);\n"
"font: 75 18pt \"MS Shell Dlg 2\";\n"
"color: rgb(170, 255, 0);"))
        self.eksi.setText(_translate("MainWindow", "-"))
        self.carpi.setStyleSheet(_translate("MainWindow", "background-color: rgb(170, 85, 0);\n"
"font: 75 18pt \"MS Shell Dlg 2\";\n"
"color: rgb(170, 255, 0);"))
        self.carpi.setText(_translate("MainWindow", "x"))
        self.esittir.setStyleSheet(_translate("MainWindow", "background-color: rgb(170, 85, 0);\n"
"font: 75 18pt \"MS Shell Dlg 2\";\n"
"color: rgb(170, 255, 0);"))
        self.esittir.setText(_translate("MainWindow", "="))
        self.bolu.setStyleSheet(_translate("MainWindow", "background-color: rgb(170, 85, 0);\n"
"font: 75 18pt \"MS Shell Dlg 2\";\n"
"color: rgb(170, 255, 0);"))
        self.bolu.setText(_translate("MainWindow", "/"))
        self.nokta.setText(_translate("MainWindow", "."))
        self.buton0.setText(_translate("MainWindow", "0"))
        self.buton6.setText(_translate("MainWindow", "6"))
        self.buton7.setText(_translate("MainWindow", "7"))
        self.buton8.setText(_translate("MainWindow", "8"))
        self.buton4.setText(_translate("MainWindow", "4"))
        self.buton5.setText(_translate("MainWindow", "5"))
        self.buton3.setText(_translate("MainWindow", "3"))
        self.buton1.setText(_translate("MainWindow", "1"))
        self.buton2.setText(_translate("MainWindow", "2"))
        self.buton9.setText(_translate("MainWindow", "9"))
        self.clear.setStyleSheet(_translate("MainWindow", "background-color: rgb(170, 85, 0);\n"
"font: 75 18pt \"MS Shell Dlg 2\";\n"
"color: rgb(170, 255, 0);"))
        self.clear.setText(_translate("MainWindow", "C"))
        self.label.setText(_translate("MainWindow", "0"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
